config/routes.rb
SchemeFinderFrontend::Application.routes.draw do
  resource :page, only: [] do
    member {
      get :about
      get :intro
      get :start
      get :maintenance
      get :cookies
      get :terms
      get :contact
    }
  end

  # allow to speficy mobile agent
  scope "(:current_agent)", current_agent: /mobile/ do
    get "schemes/new", to: "schemes#new"

    resources :terms, only: :create do
      collection {
        post :cookies
      }
    end

    scope "/:current_audience", constraints: { current_audience: /businesses|teachers/  } do
      resources :schemes, only: [:new, :create, :index] do
        collection {
          get :search
          get :mobile_search
        }

        scope module: :schemes do
          resources :feedbacks, only: [:new, :create, :index]
        end
      end

      root to: "schemes#index", as: :root_with_audience
    end
  end

  root to: "pages#start"
end

app/models/scheme.rb
class Scheme
  include SchemeFinderFrontend::ApiEntity

  attr_accessor :id,
                :had_direct_interactions,
                :logo,
                :contact_name,
                :contact_email,
                :contact_phone,
                :name,
                :website,
                :description,
                :location_ids,
                :sector_ids,
                :subject_ids,
                :audience_ids,
                :activity_ids,
                :company_size_ids,
                :age_range_ids

  def persisted?
    false
  end

  def website_url
    if (url = website).present?
      if url.starts_with?("http")
        url
      else
        "http://#{url}"
      end
    end
  end

  def logo_for_upload
    if logo.present? && logo.kind_of?(ActionDispatch::Http::UploadedFile)
      @logo = attributes['logo'] = UploadIO.new(
        logo,
        logo.content_type,
        logo.original_filename
      )
    end
  end

  def save
    resp = SchemeFinderFrontend.api_client.post(
      self.class.collection_path,
      scheme: attributes
      # { scheme: attributes.merge('logo' => logo_for_upload) }
    )

    case resp.status
    when 201
      true
    when 422
      assign_errors(resp.body['errors'])

      false
    else
      false
    end
  end
end

app/controllers/schemes/base_controller.rb
module Schemes
  class BaseController < ApplicationController

    private

    def scheme_id
      params[:scheme_id]
    end
    helper_method :scheme_id

    def scheme
      @scheme ||= Scheme.find(scheme_id)
    end
    helper_method :scheme
  end
end

app/controllers/schemes/feedbacks_controller.rb
module Schemes
  class FeedbacksController < Schemes::BaseController
    skip_before_action :set_cache_headers, only: [:create]

    def create
      @feedback = Feedback.new(feedback_params)

      if @feedback.save(scheme_id)
        redirect_to scheme_feedbacks_url(scheme_id),
                    notice: 'Feedback submitted for approval'
      else
        flash.alert = 'An issue occured on feedback submission, please check form errors'
        render :new
      end
    end

    def new
      @feedback = Feedback.new
      @back_link = session[:feedback_path]
    end

    def index
      @feedbacks = Feedback.all(scheme_id: scheme_id)
      @average_score = Feedback.average_score_for @feedbacks
      if current_agent == "mobile"
        if session[:mobile_search_path]
          @back_link = session[:mobile_search_path]
        else
            @back_link = root_with_audience_path(current_audience: params[:current_audience], current_agent: "mobile")
        end
      else
        @back_link = root_with_audience_path(current_audience: params[:current_audience], current_agent: "")
      end
      session[:feedback_path] = scheme_feedbacks_path(scheme)
    end

    private

    def feedback_params
      params.require(:feedback).permit(
        :score, :description
      )
    end
  end
end

app/controllers/schemes_controller.rb
class SchemesController < ApplicationController
  skip_before_action :set_cache_headers, only: [:new, :create]

  def create
    @scheme = Scheme.new(scheme_params)

    if @scheme.save
      flash.notice = 'Scheme submitted for approval'
      location = root_url[/[^\?]+/]
    else
      flash.alert = 'An issue occured on scheme submission, please check form errors'
      location = new_scheme_url
    end

    respond_with(@scheme, location: location)
  end

  def new
    @scheme = Scheme.new
  end

  def index
    @search = SchemeSearch.new(search_params)
    @search_results = @search.results
    @total_schemes = @search_results.total_count
    @schemes = @search_results.for_kaminari
    @back_link = root_url[/[^\?]+/]
    session[:feedback_path] = root_with_audience_path(current_audience: params[:current_audience], current_agent: "")
  end

  def search
    search_results = SchemeSearch.new(search_params).results

    render partial: "results",
           locals: {
             total_schemes: search_results.total_count,
             schemes: search_results.for_kaminari,
           }
  end

  def mobile_search
    search_results = SchemeSearch.new(search_params).results
    @total_schemes = search_results.total_count
    @schemes = search_results.for_kaminari
    @back_link = root_with_audience_path(current_audience: params[:current_audience], current_agent: "mobile")
    session[:mobile_search_path] = request.env['REQUEST_URI']
    session[:feedback_path] = session[:mobile_search_path]
  end

  private

  def search_params
    result = (params[:search] || {}).merge(params.slice(:page, :per_page))
    if current_audience
      result[:audiences] = [current_audience]
    else
      # nothing
    end

    result
  end
  helper_method :search_params

  def scheme_params
    params.require(:scheme).permit(
      :had_direct_interactions,
      :contact_name, :contact_email, :contact_phone,
      :name, :website, :description,
      location_ids: [],
      sector_ids: [],
      audience_ids: [],
      activity_ids: [],
      company_size_ids: [],
      age_range_ids: []
    )
  end
end

app/helpers/schemes_helper.rb
module SchemesHelper
  def had_direct_interactions_label
    if businesses_audience?
      "Have you engaged with schools before?"
    else
      "Have you engaged with businesses before?"
    end
  end

  def age_range_label
    if businesses_audience?
      "Age range you prefer to engage with?"
    else
      "What age range are your students?"
    end
  end

  def search_params_list(search_params)
    search_params.values
                 .flatten
                 .compact
                 .map(&:titleize)
                 .reject(&:blank?)
                 .reject{ |value| %w(0 1).include?(value) }
  end
end

app/views/schemes/_form.html.slim
= simple_form_for @scheme,
                  as: :scheme,
                  url: schemes_path,
                  html: { class: "horizontal-form" } do |f|
  .form-inputs
    /= f.input :logo, as: :file

    = f.input :contact_name, required: true
    = f.input :contact_email, required: true
    = f.input :contact_phone, required: true
    = f.input :name, required: true, label: "Scheme name"
    = f.input :website, required: true
    = f.input :description, as: :text, input_html: {rows: 5}

    = f.input :location_ids,
              as: :grouped_select,
              group_method: :last,
              label: 'Locations',
              collection: Location.collection,
              input_html: { class: "js-select2", multiple: true }

    = f.input :sector_ids,
              as: :multi_select,
              label: 'Sectors',
              collection: Sector.collection

    = f.input :subject_ids,
              as: :multi_select,
              label: 'Subjects',
              collection: Subject.collection

    = f.input :audience_ids,
              as: :multi_select,
              label: 'Audiences',
              collection: Audience.collection

    = f.input :activity_ids,
              as: :multi_select,
              label: 'Activities',
              collection: Activity.collection

    = f.input :company_size_ids,
              as: :multi_select,
              label: 'Company size',
              collection: CompanySize.collection

    = f.input :age_range_ids,
              as: :multi_select,
              label: 'Age range',
              collection: AgeRange.collection

  .form-actions.scheme-actions
    .form-control.checkbox
      input#new-scheme-accept type='checkbox'
      label for="new-scheme-accept"
        p
          ' By ticking this box, you confirm the following
        ul
          li
            ' The information regarding your scheme that you have submitted for inclusion on this website is complete and correct. 
          li
            ' You have undertaken any necessary due diligence regarding any partner organisations that work with you to satisfy yourself that they are reputable and competent.
          li
            ' You have carried out all necessary health and safety audits, risk assessments and background checks required by UK law to the extent that they are applicable to your organisation.
          li
            ' You will regularly update your profile to ensure that any information that appears about your organisation on the website is accurate and up to date. You understand that the Growing Ambitions Tool is a publicly available service and BIS does not carry out any screening or checks on the users of the site.
          li
            ' You agree to indemnify, and to keep indemnified, BIS and EETf against all losses, liabilities, costs (including legal costs) and expenses where such losses, liabilities, costs and expenses are due to the acts or omissions of your organisation or of any partner organisations participating in your scheme.

    = f.button :submit,
               class: "btn btn-primary",
               id: "submit_btn",
               disabled: true,
               data: { action: "submit", disable_with: "Working" }
    .clear

app/views/schemes/_mobile_search_filters.html.slim
- if search_params_list(search_params).any?
  ul.tags-list
    - search_params_list(search_params).each do | tag |
      li
        span= tag
        = link_to "✕"

app/views/schemes/_results.html.slim
.inner-block
  = render "search_summary", total_schemes: total_schemes

  - if total_schemes == 0 # no search results
    .no-matching-schemes
      h2
        | There are no matching schemes.
      p
        | Try making your search broader and try again.
  - else
    ul.results-list
      - schemes.each do |scheme|
        = render "scheme", scheme: scheme

    = paginate schemes

app/views/schemes/_scheme.html.slim
li.scheme
  h3.mobile-hide
    = link_to scheme.name,
              scheme.website_url,
              target: "_blank",
              data: { ga_scheme_click: true,
                      ga_tool_completed: true }
  h3.mobile-show
    = link_to scheme.name,
              scheme.website_url,
              target: "_system",
              data: { ga_scheme_click: true,
                      ga_tool_completed: true }

  = simple_format scheme.description
/
  = link_to "Leave feedback",
            [:new, scheme, :feedback],
            class: "btn feedback-link",
            data: { action: "leave_feedback" }
  = link_to "View feeback",
            [scheme, :feedbacks],
            class: "btn feedback-link",
            data: { action: "show_feedback" }

app/views/schemes/_search.html.slim
= simple_form_for search,
                  as: :search,
                  url: url,
                  method: :get,
                  remote: remote,
                  defaults: { wrapper_html: { class: "filter" } },
                  html: { class: "horizontal-form scheme-search-form" } do |f|

  fieldset
    .had-direct-interactions-container data-wraps="had-direct-interactions"
      = f.input :had_direct_interactions,
                as: :boolean,
                label: had_direct_interactions_label,
                input_html: { data: { register: "had-direct-interactions" } }

      - if businesses_audience?
        select#company-size-for-evaluation-purposes.company-size-for-evaluation-purposes.js-select2 data-placeholder="Select your company size"
          option
          - %w(0-9 10-249 250-500 501-1000 1000+).each do |size|
            option value="#{size}" = "#{size} employees"

      .hint
        ' For evaluation purposes

    = f.input :locations,
              as: :grouped_select,
              group_method: :last,
              label: 'Locations',
              placeholder: 'Locations',
              collection: Location.collection,
              required: false,
              input_html: { class: "multi-row-select js-select2", multiple: true }

    = f.input :sectors,
              as: :multi_select,
              label: 'Sectors',
              placeholder: 'Sectors',
              collection: Sector.collection,
              required: false,
              input_html: { class: "multi-row-select" }

    - for_teachers do
      = f.input :subjects,
                as: :multi_select,
                label: 'Subjects',
              placeholder: 'Subjects',
                collection: Subject.collection,
                required: false,
                input_html: { class: "multi-row-select" }

    - unless current_audience
      = f.input :audiences,
                as: :multi_select,
                label: 'Audiences',
              placeholder: 'Audiences',
                collection: Audience.collection,
                required: false,
                input_html: { class: "multi-row-select" }

    = f.input :activities,
              as: :multi_select,
              collection: Activity.collection,
              label: 'Activities',
              placeholder: 'Activities',
              label_method: "for_#{current_audience}",
              required: false,
              input_html: { class: "multi-row-select" }

    = f.input :age_ranges,
              as: :multi_select,
              label: age_range_label,
              placeholder: age_range_label,
              collection: AgeRange.collection,
              required: false,
              input_html: { class: "multi-row-select" }
  - for_mobile do
    .form-actions
      = f.button :submit, "Search for Schemes",
                 class: "btn-search button btn btn-primary #{'btn-businesses' if businesses_audience?}#{'btn-teachers' if teachers_audience?}",
                 id: "submit_btn",
                 data: { action: "submit",
                         ga_search_scheme_click: "true" }
      .clear

app/views/schemes/_search_summary.html.slim
.filter-results-summary.mobile-hide[aria-live="polite" aria-atomic="true"]
  h3
    span.results-count
      = total_schemes
    |  Available schemes

app/views/schemes/_terms.html.slim
#terms-container
  .terms-overlay
  .terms-contents
    = form_tag terms_path, remote: true do
      = hidden_field_tag :authenticity_token, form_authenticity_token

      .terms-body
        h2 Growing Ambitions – Disclaimers
        - if businesses_audience?
          h3
            ' Disclaimer for businesses
          = render "pages/terms_businesses"
        - else
          h3
            ' Disclaimer for schools
          = render "pages/terms_teachers"
      .terms-footer
        .form-control
          = check_box_tag "accept", "1", false, id: "terms-accept"
          label for="terms-accept" Confirm and accept Terms & Conditions
        - if businesses_audience?
          = submit_tag "Get Started for Businesses", class: "big button btn-businesses", id: "terms-accepted"
        - else
          = submit_tag "Get Started for Teachers", class: "big button btn-teachers", id: "terms-accepted"
      .terms-fade

app/views/schemes/index.html.slim
= content_for :body_classes do
  = yield(:body_classes).concat(" search-page ")

- for_web do
  .article-container.group.scheme-finder-search
    - if businesses_audience?
      h1 For Businesses
      h2 We help businesses connect with schools, engage with pupils, enrich learning and showcase industry to the next generation of young people.
    - else
      h1 For Teachers
      h2 We help teachers to identify suitable schemes that provide curriculum supported lesson plans, careers advice, local visits and work experience.

    hr

    .block-2
      .inner-block
        p.intro-text You can use the filters to only show schemes that you are eligible for
        .filter-block
          = render "search",
                   search: @search,
                   remote: true,
                   url: search_schemes_path

        /.want-submit-own-scheme.mobile-hide
          h3
            | Want to submit your own scheme?
          = link_to "Submit scheme application",
                    new_scheme_path,
                    class: "button"

    #filtered-results.block-4.filtered-results
      = render "results",
               total_schemes: @total_schemes,
               schemes: @schemes

- for_mobile do
  .scheme-finder-mobile-search
    - if businesses_audience?
      h1 For Businesses
      h2 We help businesses connect with schools, engage with pupils, enrich learning and showcase industry to the next generation of young people.
    - else
      h1 For Teachers
      h2 We help teachers to identify suitable schemes that provide curriculum supported lesson plans, careers advice, local visits and work experience.

    hr

    .block-2
      .inner-block
        .filter-block
          = render "search",
                   search: @search,
                   remote: false,
                   url: mobile_search_schemes_path

#terms-container.hidden
  .terms-overlay
  .terms-contents
    .terms-body
      h2 Growing Ambitions – Disclaimers
      - if businesses_audience?
        h3
          ' Disclaimer for businesses
        = render "pages/terms_businesses"
      - else
        h3
          ' Disclaimer for schools
        = render "pages/terms_teachers"
    .terms-footer
      .form-control
        input#terms-accept type='checkbox'
        label for="terms-accept" Confirm and accept Terms & Conditions
      - if businesses_audience?
        = link_to "Get Started for Businesses", "#", class: "big button btn-businesses", disabled: true, id: "terms-accepted-btn"
      - else
        = link_to "Get Started for Teachers", "#", class: "big button btn-teachers", disabled: true, id: "terms-accepted-btn"
    .terms-fade

app/views/schemes/mobile_search.html.slim
= content_for :body_classes do
  = yield(:body_classes).concat(" search-page ")

.search-results
  = render "mobile_search_filters"

  #filtered-results.filtered-results
    = render "results",
             total_schemes: @total_schemes,
             schemes: @schemes

app/views/schemes/new.html.slim
#new-scheme-page
  .page-header
    h1 Scheme application

  .block-6
    = render "form"

    .clear