config/routes.rb
SchemeFinderFrontend::Application.routes.draw do
  resource :page, only: [] do
    member {
      get :about
      get :intro
      get :start
      get :maintenance
      get :cookies
      get :terms
      get :contact
    }
  end

  # allow to speficy mobile agent
  scope "(:current_agent)", current_agent: /mobile/ do
    get "schemes/new", to: "schemes#new"

    resources :terms, only: :create do
      collection {
        post :cookies
      }
    end

    scope "/:current_audience", constraints: { current_audience: /businesses|teachers/  } do
      resources :schemes, only: [:new, :create, :index] do
        collection {
          get :search
          get :mobile_search
        }

        scope module: :schemes do
          resources :feedbacks, only: [:new, :create, :index]
        end
      end

      root to: "schemes#index", as: :root_with_audience
    end
  end

  root to: "pages#start"
end

app/views/pages/_terms_businesses.html.slim
p
  ' The Growing Ambitions website has been developed, and is maintained, by the Department for Business, Innovation and Skills in partnership with the Education and Employers Taskforce.  References to “we”, “us” and “our” in this disclaimer are references to the Department for Business, Innovation and Skills and the Education and Employers Taskforce  

p
  ' We have selected scheme providers in order to facilitate placements of students with businesses.  The scheme providers have been included on the basis of the scheme providers’ publicly available data.  

p
  ' Our role is limited to funding a website intended to facilitate engagement between schools and businesses.  We do not:

ul
  li
    p
      ' Endorse the scheme providers, or engage in the process of selecting schools to participate in the schemes (which is a decision for the scheme providers);
  li
    p
      ' Endorse the suitability of the schools for the placements that you are offering;
  li
    p
      ' Make any representations or assurances about the quality of the schools (or individuals from those schools) which participate in placements with your business; or
  li
    p
      ' Provide any assurances that the placements will deliver you with the outcomes you are seeking to achieve by participating in the scheme.

p
  ' Your decision to participate in the scheme is done entirely at your own risk and you must take whatever steps/make any investigations you consider necessary to satisfy yourself that the scheme providers, participating schools and your participation in the scheme are suitable for your purposes.

p
  ' In order to participate in the scheme you must confirm that you have read and understood the terms of this disclaimer.

app/views/pages/_terms_teachers.html.slim
p
  ' The Growing Ambitions website has been developed, and is maintained, by the Department for Business, Innovation and Skills in partnership with the Education and Employers Taskforce  References to “we”, “us” and “our” in this disclaimer are references to the Department for Business, Innovation and Skills and the Education and Employers Taskforce.

p
  ' We have selected scheme providers in order to facilitate placements of students with businesses.  The scheme providers have been included on the basis of the scheme providers’ publicly available data.    

p
  ' Our role is limited to funding a website intended to facilitate engagement between schools and businesses.  We do not:

ul
  li
    p
      ' Endorse the scheme providers, or engage in the process of selecting businesses to participate in the schemes (which is a decision for the scheme providers);
  li
    p
      ' Endorse the suitability of the schemes for your purposes;
  li
    p
      ' Make any representations or assurances about the quality or content of the placements offered by the scheme providers and participating businesses; or
  li
    p
      ' Provide any assurances that you will achieve the outcomes that you are seeking to achieve by participating in the scheme.

p
  ' Your decision to participate in the scheme is done entirely at your own risk and you must take whatever steps/make any investigations you consider necessary to satisfy yourself that the scheme providers, participating businesses and placements are suitable for your purposes.

p
  ' In order to participate in the scheme you must confirm that you have read and understood the terms of this disclaimer.

app/views/pages/about.html.slim
- content_for :title do
  | About

.static-page
  h1 About

  p
    ' The Growing Ambitions tool is developed and maintained by the Department for Business, Innovation and Skills in partnership with the Education and Employers Taskforce.

  p
    'The online tools for employers and teachers are intended to make it easier for businesses and schools to decide which scheme to engage with, and what level of engagement best meets their needs.

  p
    'For businesses it will provide personalised recommendations based on the resources available and location.

  p
    'For teachers it will connect them with schemes that offer curriculum-led materials to suit their needs, such as lesson plans, lesson support, careers inspiration and local visits.

app/views/pages/contact.html.slim
- content_for :title do
  | Contact

.static-page
  h1 Contact

app/views/pages/cookies.html.slim
- content_for :title do
  | Cookie Policy

.static-page
  h1 Cookie Policy

  p
    ' When someone visits this website we collect standard internet log information and details of visitor behaviour patterns. We do this to find out things such as the number of visitors to the various parts of the site. We collect this information in a way which does not identify anyone. We do not make any attempt to find out the identities of those visiting our website. We will not associate any data gathered from this site with any personally identifying information from any source. If we do want to collect personally identifiable information through our website, we will be up front about this. We will make it clear when we collect personal information and will explain what we intend to do with it.

  h3 Use of cookies by Growing Ambitions:

  p
    ' Cookies are small text files that are placed on your computer by websites that you visit. They are widely used in order to make websites work, or work more efficiently, as well as to provide information to the owners of the site. If you do not want a cookie you can set your browser to deny it.

  p
    ' We use cookies from Google Analytics to understand how people find our websites, what content they view and how long they stay on the site. This is to enable us to improve functionality, navigation and content for our users.

  p
    ' The table below explains the cookies we use and why.

  h3 Google Analytics Cookies 

  table.table-bordered
    tbody
      tr
        th
          ' Utmz
        td
          ' Tracks where the visitor came from e.g. search engine or referring page or keyword.
      tr
        th
          ' Utma
        td
          ' Tracks each users number of visits, first visit, last visit.
      tr
        th
          ' Utmb and Utmc
        td
          ' Track when a visit starts and ends.

  p
    ' Most web browsers allow some control of most cookies through the browser settings. To find out more about cookies, including how to see what cookies have been set and how to manage and delete them, visit 
    = link_to "www.aboutcookies.org", "http://www.aboutcookies.org"
    '  or 
    = link_to "www.allaboutcookies.org", "http://www.allaboutcookies.org"
    ' .

app/views/pages/intro.html.slim
= content_for :body_classes do
  = yield(:body_classes).concat(" intro-page ")

= link_to "Start", start_page_path, class: "big button"

app/views/pages/maintenance.html.slim
= content_for :body_classes do
  = yield(:body_classes).concat(" intro-page ")

p
  | We are currently down for maintenance. Will be back soon.

app/views/pages/start.html.slim
= content_for :body_classes do
  = yield(:body_classes).concat(" start-page ")

.inner
  section.intro
    .get-started-intro
      h1
        ' Welcome to
        br.visible-iphone-portrait
        ' Growing Ambitions
      p The best place for teachers and businesses to find schemes aimed at young people.

      .partnership-container
        p
          strong In partnership with:
        p
          ' Education and Employers Taskforce
        p
          ' Department of Business, Innovation and Skills
    hr
    .pull-left.for-business
      h3 For Businesses
      p We help businesses connect with schools, engage with pupils, enrich learning and showcase industry to the next generation of young people.
      .mobile-hide
        = link_to "Get Started for Businesses",
                  root_with_audience_path(current_audience: "businesses",
                                          current_agent: ""),
                  class: "big button btn-businesses",
                  id: "btn-businesses-guide"
      .mobile-show
        = link_to "Get Started for Businesses",
                  root_with_audience_path(current_audience: "businesses",
                                          current_agent: "mobile"),
                  class: "big button btn-businesses",
                  id: "btn-businesses-guide"

    .pull-right.for-teachers
      h3 For Teachers
      p We help teachers to identify suitable schemes that provide curriculum supported lesson plans, careers advice, local visits and work experience.
      .mobile-hide
        = link_to "Get Started for Teachers",
                  root_with_audience_path(current_audience: "teachers",
                                          current_agent: ""),
                  class: "big button btn-teachers",
                  id: "btn-teachers-guide"
      .mobile-show
        = link_to "Get Started for Teachers",
                  root_with_audience_path(current_audience: "teachers",
                                          current_agent: "mobile"),
                  class: "big button btn-teachers",
                  id: "btn-teachers-guide"
    .clear

    hr

    .pull-left.register-title
      h3 Register a Scheme
    .pull-right.register-content
      p
        ' Please help us to identify sector or company led programmes aimed at inspiring enterprise to young people and schools.
        = link_to 'Register a Scheme', schemes_new_path, class: "register-link"

    .pull-left.register-title.clear
      h3 Comments
    .pull-right.register-content
      p
        ' If you wish to report an error or make a correction on any scheme listing we would be grateful if you can email any details to the promotion of manufacturing team at Department of Business, Innovation and Skills by clicking
        = link_to "this link.", "mailto:growingambitions@bis.gsi.gov.uk"

app/views/pages/terms.html.slim
- content_for :title do
  | Terms & Conditions

.static-page
  h1 Growing Ambitions – Disclaimers

  h3
    ' 1. Disclaimer for schools
  = render "terms_teachers"

  h3
    ' 2. Disclaimer for businesses
  = render "terms_businesses"