config/routes.rb
SchemeFinderFrontend::Application.routes.draw do
  resource :page, only: [] do
    member {
      get :about
      get :intro
      get :start
      get :maintenance
      get :cookies
      get :terms
      get :contact
    }
  end

  # allow to speficy mobile agent
  scope "(:current_agent)", current_agent: /mobile/ do
    get "schemes/new", to: "schemes#new"

    resources :terms, only: :create do
      collection {
        post :cookies
      }
    end

    scope "/:current_audience", constraints: { current_audience: /businesses|teachers/  } do
      resources :schemes, only: [:new, :create, :index] do
        collection {
          get :search
          get :mobile_search
        }

        scope module: :schemes do
          resources :feedbacks, only: [:new, :create, :index]
        end
      end

      root to: "schemes#index", as: :root_with_audience
    end
  end

  root to: "pages#start"
end

app/views/layouts/_cookies.html.slim
#cookie-container
  = form_tag cookies_terms_path, remote: true do
    = hidden_field_tag :authenticity_token, form_authenticity_token

    .container
      i.icon-info
      .cookie-contents
        h3 Cookie Policy
        p
          ' Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          br.visible-sm
          br.visible-sm
          = link_to "Find out more »", cookies_page_path
      .cookie-btn
        = submit_tag "Accept & Close", class: "btn"

app/views/layouts/application.html.slim
= content_for :head do
  == stylesheet_link_tag "application", media: "all"
  /[if IE 6]
    = stylesheet_link_tag "application-ie6"
  /[if IE 7]
    = stylesheet_link_tag "application-ie7"
  /[if IE 8]
    = stylesheet_link_tag "application-ie8"
  /[if IE 9]
    = stylesheet_link_tag "application-ie9"
  meta name="controller-class" content=js_controller_class
  meta name="controller-action" content=js_controller_action
  meta name="current_agent" content=js_current_agent
  meta name="current_audience" content=js_current_audience
  meta http-equiv="content-type" content="text/html; charset=UTF-8"
  meta content="minimal-ui, width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport"
  = csrf_meta_tags unless response.cache_control[:public]
  = content_for :favicon do
    link rel="shortcut icon" href="#{ asset_path 'favicon.ico' }" type="image/x-icon"

= content_for :page_title do
  ' Growing Ambitions

= content_for :after_header do
  = render 'messages'

= content_for :body_classes, "mainstream"

= content_for :inside_header do
  = inside_header_content

= content_for :body_classes do
  - if businesses_audience?
    '  scheme-businesses
  - if teachers_audience?
    '  scheme-teachers

= content_for :content do
  #wrapper.scheme-finder-frontend
    #ipad-check
    #ios-check.visible-iphone
    - unless %w(pages).include? controller_name
      #back-banner.mobile-show
        = link_to "←", @back_link

    main#content.group role="main"
      - if content_for? :inside_header
        header.page-header.group
          div
            h1
              = link_to "Growing Ambitions", root_path
            .pull-right
              p Learning, Connecting and Inspiring

      .article-container.group
        article.group[role="article"]
          = yield

  #cookie-container.hidden
    .container
      i.icon-info
      .cookie-contents
        h3 Cookie Policy
        p
          ' We use cookies from Google Analytics to understand how people find our websites, what content they view and how long they stay on the site. This is to enable us to improve functionality, navigation and content for our users. &nbsp;
          br.visible-sm
          br.visible-sm
          = link_to "Find out more »", cookies_page_path
      .cookie-btn
        = link_to "Accept & Close", "#", class: 'btn', id: "cookie-close-btn"

= content_for :footer_top do
  .pull-left
    ul
      li = link_to "About #{yield(:page_title)}", about_page_path
      li = link_to "Terms & Conditions", terms_page_path
      li = link_to "Cookie Policy", cookies_page_path
      li = link_to "Contact", "mailto:growingambitions@bis.gsi.gov.uk"
  .pull-right
    ' © #{yield(:page_title)} #{Time.now.year}
  .clear

= content_for :body_end do
  = javascript_include_tag "application"
  = google_analytics_init

= render template: 'layouts/govuk_template'